# Process the Test Results
## Imports and Helpers

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

---

## Reading Data

In [5]:
res = pd.read_csv('All Test Results.csv')
res.head()

,Repo,Function,Model,Type,Total Passed Before,Total Passed After,Total Failed Before,Total Failed After,Function Passed Before,Function Passed After,Function Failed Before,Function Failed After,Total Passed H,Function Passes H
0,craftship_codebox-npm,function 1: github.js,Artigenz-Coder-DS-6_7B,type 1,91,79.0,0,12.0,12,0.0,0,12.0,79.0,0.0
1,craftship_codebox-npm,function 1: github.js,Artigenz-Coder-DS-6_7B,type 2,91,79.0,0,12.0,12,0.0,0,12.0,79.0,0.0
2,craftship_codebox-npm,function 1: github.js,Artigenz-Coder-DS-6_7B,type 3,91,79.0,0,12.0,12,0.0,0,12.0,79.0,0.0
3,craftship_codebox-npm,function 1: github.js,CodeQwen1_5-7B-Chat,type 1,91,79.0,0,12.0,12,0.0,0,12.0,79.0,0.0
4,craftship_codebox-npm,function 1: github.js,CodeQwen1_5-7B-Chat,type 2,91,79.0,0,12.0,12,0.0,0,12.0,79.0,0.0

---
## Processing Data

In [6]:
res["Total Passed Before Percentage"] = (res["Total Passed Before"] / (res["Total Passed Before"] + res["Total Failed Before"])) * 100
res["Total Passed After Percentage"] = (res["Total Passed After"] / (res["Total Passed After"] + res["Total Failed After"])) * 100
res["Function Passed Before Percentage"] = (res["Function Passed Before"] / (res["Function Passed Before"] + res["Function Failed Before"])) * 100
res["Function Passed After Percentage"] = (res["Function Passed After"] / (res["Function Passed After"] + res["Function Failed After"])) * 100

res["Human Intervention Repo Level"] = (res["Total Passed H"] / (res["Total Passed Before"] + res["Total Failed Before"])) * 100
res["Human Intervention Function Level"] = (res["Function Passes H"] / (res["Function Passed Before"] + res["Function Failed Before"])) * 100

res.head()

,Repo,Function,Model,Type,Total Passed Before,Total Passed After,Total Failed Before,Total Failed After,Function Passed Before,Function Passed After,Function Failed Before,Function Failed After,Total Passed H,Function Passes H,Total Passed Before Percentage,Total Passed After Percentage,Function Passed Before Percentage,Function Passed After Percentage,Human Intervention Repo Level,Human Intervention Function Level
0,craftship_codebox-npm,function 1: github.js,Artigenz-Coder-DS-6_7B,type 1,91,79.0,0,12.0,12,0.0,0,12.0,79.0,0.0,100.0,86.813187,100.0,0.0,86.813187,0.0
1,craftship_codebox-npm,function 1: github.js,Artigenz-Coder-DS-6_7B,type 2,91,79.0,0,12.0,12,0.0,0,12.0,79.0,0.0,100.0,86.813187,100.0,0.0,86.813187,0.0
2,craftship_codebox-npm,function 1: github.js,Artigenz-Coder-DS-6_7B,type 3,91,79.0,0,12.0,12,0.0,0,12.0,79.0,0.0,100.0,86.813187,100.0,0.0,86.813187,0.0
3,craftship_codebox-npm,function 1: github.js,CodeQwen1_5-7B-Chat,type 1,91,79.0,0,12.0,12,0.0,0,12.0,79.0,0.0,100.0,86.813187,100.0,0.0,86.813187,0.0
4,craftship_codebox-npm,function 1: github.js,CodeQwen1_5-7B-Chat,type 2,91,79.0,0,12.0,12,0.0,0,12.0,79.0,0.0,100.0,86.813187,100.0,0.0,86.813187,0.0

In [ ]:
res.drop(columns=["Total Passed H", "Function Passes H"], inplace=True)
res.dropna(inplace=True)

In [10]:
res = res[['Model', 'Repo', 'Type', 'Function', 'Total Passed Before Percentage', 'Total Passed After Percentage', 'Function Passed Before Percentage', 'Function Passed After Percentage', 'Human Intervention Repo Level', 'Human Intervention Function Level']]
res.head(15)

,Model,Repo,Type,Function,Total Passed Before Percentage,Total Passed After Percentage,Function Passed Before Percentage,Function Passed After Percentage,Human Intervention Repo Level,Human Intervention Function Level
0,Artigenz-Coder-DS-6_7B,craftship_codebox-npm,type 1,function 1: github.js,100.0,86.813187,100.0,0.0,86.813187,0.0
1,Artigenz-Coder-DS-6_7B,craftship_codebox-npm,type 2,function 1: github.js,100.0,86.813187,100.0,0.0,86.813187,0.0
2,Artigenz-Coder-DS-6_7B,craftship_codebox-npm,type 3,function 1: github.js,100.0,86.813187,100.0,0.0,86.813187,0.0
3,CodeQwen1_5-7B-Chat,craftship_codebox-npm,type 1,function 1: github.js,100.0,86.813187,100.0,0.0,86.813187,0.0
4,CodeQwen1_5-7B-Chat,craftship_codebox-npm,type 2,function 1: github.js,100.0,86.813187,100.0,0.0,86.813187,0.0
5,CodeQwen1_5-7B-Chat,craftship_codebox-npm,type 3,function 1: github.js,100.0,0.000000,100.0,0.0,86.813187,0.0
6,DeepSeek-Coder-V2,craftship_codebox-npm,type 1,function 1: github.js,100.0,0.000000,100.0,0.0,86.813187,0.0
7,DeepSeek-Coder-V2,craftship_codebox-npm,type 2,function 1: github.js,100.0,86.813187,100.0,0.0,86.813187,0.0
8,DeepSeek-Coder-V2,craftship_codebox-npm,type 3,function 1: github.js,100.0,86.813187,100.0,0.0,86.813187,0.0
9,GPT-3_5-Turbo,craftship_codebox-npm,type 1,function 1: github.js,100.0,86.813187,100.0,0.0,86.813187,0.0
10,GPT-3_5-Turbo,craftship_codebox-npm,type 2,function 1: github.js,100.0,86.813187,100.0,0.0,86.813187,0.0
11,GPT-3_5-Turbo,craftship_codebox-npm,type 3,function 1: github.js,100.0,86.813187,100.0,0.0,86.813187,0.0
12,GPT-4,craftship_codebox-npm,type 1,function 1: github.js,100.0,0.000000,100.0,0.0,86.813187,0.0
13,GPT-4,craftship_codebox-npm,type 2,function 1: github.js,100.0,86.813187,100.0,0.0,86.813187,0.0
14,GPT-4,craftship_codebox-npm,type 3,function 1: github.js,100.0,86.813187,100.0,0.0,86.813187,0.0

In [12]:
res = res.sort_values(by=['Model', 'Repo', 'Type', 'Function'], ascending=[True, False, True, True])
res.drop('Function', axis=1, inplace=True)
res1 = res.groupby(['Model', 'Repo', 'Type']).mean().reset_index()
res1.head(55)

,Model,Repo,Type,Total Passed Before Percentage,Total Passed After Percentage,Function Passed Before Percentage,Function Passed After Percentage,Human Intervention Repo Level,Human Intervention Function Level
0,Artigenz-Coder-DS-6_7B,JuliaRegistries_Tagbot,type 1,93.333333,0.000000,100.0,0.000000,0.000000,0.000000
1,Artigenz-Coder-DS-6_7B,JuliaRegistries_Tagbot,type 2,93.333333,82.666667,100.0,0.000000,82.666667,0.000000
2,Artigenz-Coder-DS-6_7B,StackJanitor,type 1,100.000000,67.567568,100.0,0.000000,67.567568,0.000000
3,Artigenz-Coder-DS-6_7B,StackJanitor,type 2,100.000000,67.567568,100.0,0.000000,67.567568,0.000000
4,Artigenz-Coder-DS-6_7B,StackJanitor,type 3,100.000000,67.567568,100.0,0.000000,67.567568,0.000000
5,Artigenz-Coder-DS-6_7B,craftship_codebox-npm,type 1,100.000000,28.937729,100.0,0.000000,60.073260,0.000000
6,Artigenz-Coder-DS-6_7B,craftship_codebox-npm,type 2,100.000000,28.937729,100.0,0.000000,91.941392,0.000000
7,Artigenz-Coder-DS-6_7B,craftship_codebox-npm,type 3,100.000000,60.073260,100.0,0.000000,93.406593,0.000000
8,Artigenz-Coder-DS-6_7B,laconiajs_laconia,type 1,100.000000,74.358974,100.0,0.000000,74.358974,0.000000
9,Artigenz-Coder-DS-6_7B,laconiajs_laconia,type 2,100.000000,74.358974,100.0,0.000000,74.358974,0.000000
10,Artigenz-Coder-DS-6_7B,laconiajs_laconia,type 3,100.000000,74.358974,100.0,0.000000,74.358974,0.000000
11,CodeQwen1_5-7B-Chat,JuliaRegistries_Tagbot,type 1,93.333333,0.000000,100.0,0.000000,0.000000,0.000000
12,CodeQwen1_5-7B-Chat,JuliaRegistries_Tagbot,type 2,93.333333,82.666667,100.0,0.000000,86.666667,37.500000
13,CodeQwen1_5-7B-Chat,StackJanitor,type 1,100.000000,68.468468,100.0,11.111111,68.468468,11.111111
14,CodeQwen1_5-7B-Chat,StackJanitor,type 2,100.000000,67.567568,100.0,0.000000,70.270270,33.333333
15,CodeQwen1_5-7B-Chat,StackJanitor,type 3,100.000000,67.567568,100.0,0.000000,70.270270,33.333333
16,CodeQwen1_5-7B-Chat,craftship_codebox-npm,type 1,100.000000,28.937729,100.0,0.000000,60.073260,0.000000
17,CodeQwen1_5-7B-Chat,craftship_codebox-npm,type 2,100.000000,28.937729,100.0,0.000000,93.040293,16.666667
18,CodeQwen1_5-7B-Chat,craftship_codebox-npm,type 3,100.000000,64.102564,100.0,22.222222,95.604396,66.666667
19,CodeQwen1_5-7B-Chat,laconiajs_laconia,type 1,100.000000,74.358974,100.0,0.000000,74.358974,0.000000
20,CodeQwen1_5-7B-Chat,laconiajs_laconia,type 2,100.000000,74.358974,100.0,0.000000,74.358974,0.000000
21,CodeQwen1_5-7B-Chat,laconiajs_laconia,type 3,100.000000,74.358974,100.0,0.000000,74.358974,0.000000
22,DeepSeek-Coder-V2,JuliaRegistries_Tagbot,type 1,93.333333,82.666667,100.0,0.000000,86.666667,37.500000
23,DeepSeek-Coder-V2,JuliaRegistries_Tagbot,type 2,93.333333,82.666667,100.0,0.000000,90.666667,50.000000
24,DeepSeek-Coder-V2,StackJanitor,type 1,100.000000,67.567568,100.0,0.000000,81.081081,33.333333
25,DeepSeek-Coder-V2,StackJanitor,type 2,100.000000,67.567568,100.0,0.000000,90.090090,62.500000
26,DeepSeek-Coder-V2,StackJanitor,type 3,100.000000,75.675676,100.0,0.000000,95.495495,79.166667
27,DeepSeek-Coder-V2,craftship_codebox-npm,type 1,100.000000,31.868132,100.0,0.000000,91.941392,0.000000
28,DeepSeek-Coder-V2,craftship_codebox-npm,type 2,100.000000,91.941392,100.0,0.000000,94.505495,41.666667
29,DeepSeek-Coder-V2,craftship_codebox-npm,type 3,100.000000,94.139194,100.0,38.888889,95.604396,66.666667
30,DeepSeek-Coder-V2,laconiajs_laconia,type 1,100.000000,74.358974,100.0,0.000000,74.358974,0.000000
31,DeepSeek-Coder-V2,laconiajs_laconia,type 2,100.000000,74.358974,100.0,0.000000,74.358974,0.000000
32,DeepSeek-Coder-V2,laconiajs_laconia,type 3,100.000000,74.358974,100.0,0.000000,79.487179,66.666667
33,GPT-3_5-Turbo,JuliaRegistries_Tagbot,type 1,93.333333,0.000000,100.0,0.000000,84.000000,12.500000
34,GPT-3_5-Turbo,JuliaRegistries_Tagbot,type 2,93.333333,82.666667,100.0,0.000000,90.666667,50.000000
35,GPT-3_5-Turbo,StackJanitor,type 1,100.000000,67.567568,100.0,0.000000,78.378378,0.000000
36,GPT-3_5-Turbo,StackJanitor,type 2,100.000000,67.567568,100.0,0.000000,76.576577,62.500000
37,GPT-3_5-Turbo,StackJanitor,type 3,100.000000,67.567568,100.0,0.000000,76.576577,62.500000
38,GPT-3_5-Turbo,craftship_codebox-npm,type 1,100.000000,60.805861,100.0,0.000000,91.941392,0.000000
39,GPT-3_5-Turbo,craftship_codebox-npm,type 2,100.000000,60.805861,100.0,0.000000,94.871795,55.555556
40,GPT-3_5-Turbo,craftship_codebox-npm,type 3,100.000000,60.805861,100.0,11.111111,95.604396,66.666667
41,GPT-3_5-Turbo,laconiajs_laconia,type 1,100.000000,74.358974,100.0,0.000000,74.358974,0.000000
42,GPT-3_5-Turbo,laconiajs_laconia,type 2,100.000000,74.358974,100.0,0.000000,76.923077,33.333333
43,GPT-3_5-Turbo,laconiajs_laconia,type 3,100.000000,74.358974,100.0,0.000000,94.871795,62.500000
44,GPT-4,JuliaRegistries_Tagbot,type 1,93.333333,0.000000,100.0,0.000000,89.333333,62.500000
45,GPT-4,JuliaRegistries_Tagbot,type 2,93.333333,0.000000,100.0,0.000000,90.666667,50.000000
46,GPT-4,StackJanitor,type 1,100.000000,67.567568,100.0,0.000000,75.675676,0.000000
47,GPT-4,StackJanitor,type 2,100.000000,67.567568,100.0,0.000000,90.090090,62.500000
48,GPT-4,StackJanitor,type 3,100.000000,67.567568,100.0,0.000000,86.486486,62.500000
49,GPT-4,craftship_codebox-npm,type 1,100.000000,31.868132,100.0,0.000000,91.941392,0.000000
50,GPT-4,craftship_codebox-npm,type 2,100.000000,60.805861,100.0,0.000000,62.271062,33.333333
51,GPT-4,craftship_codebox-npm,type 3,100.000000,93.772894,100.0,30.555556,95.604396,66.666667
52,GPT-4,laconiajs_laconia,type 1,100.000000,74.358974,100.0,0.000000,76.923077,33.333333
53,GPT-4,laconiajs_laconia,type 2,100.000000,74.358974,100.0,0.000000,100.000000,100.000000
54,GPT-4,laconiajs_laconia,type 3,100.000000,74.358974,100.0,0.000000,87.179487,20.833333

In [13]:
res2 = res1.rename(columns={
    'Total Passed Before Percentage': 'Repo Level - Before',
    'Total Passed After Percentage': 'Repo Level - After - WH',
    'Function Passed Before Percentage': 'Function Level - Before',
    'Function Passed After Percentage': 'Function Level - After - WH',
    'Human Intervention Repo Level': 'Repo Level - After - H',
    'Human Intervention Function Level': 'Function Level - After - H'
})
res2.head()

,Model,Repo,Type,Repo Level - Before,Repo Level - After - WH,Function Level - Before,Function Level - After - WH,Repo Level - After - H,Function Level - After - H
0,Artigenz-Coder-DS-6_7B,JuliaRegistries_Tagbot,type 1,93.333333,0.000000,100.0,0.0,0.000000,0.0
1,Artigenz-Coder-DS-6_7B,JuliaRegistries_Tagbot,type 2,93.333333,82.666667,100.0,0.0,82.666667,0.0
2,Artigenz-Coder-DS-6_7B,StackJanitor,type 1,100.000000,67.567568,100.0,0.0,67.567568,0.0
3,Artigenz-Coder-DS-6_7B,StackJanitor,type 2,100.000000,67.567568,100.0,0.0,67.567568,0.0
4,Artigenz-Coder-DS-6_7B,StackJanitor,type 3,100.000000,67.567568,100.0,0.0,67.567568,0.0

### Pivoting the Data

In [17]:
res_pivot = res2.pivot_table(index=['Model', 'Repo'],
                                columns='Type',
                                values=[
                                    'Repo Level - Before',
                                    'Function Level - Before',
                                    'Repo Level - After - WH', 'Function Level - After - WH',
                                    'Repo Level - After - H', 'Function Level - After - H'
                                ])

res_pivot = res_pivot.sort_index(axis=1, level=[1, 0])
res_pivot.columns = [f'{lvl2} - {lvl1}' for lvl1, lvl2 in res_pivot.columns]
res_pivot = res_pivot.reset_index()
res_pivot = res_pivot.sort_values(by=['Model', 'Repo'], ascending=[True, False])
res_pivot.drop(columns=['type 2 - Repo Level - Before', 'type 3 - Repo Level - Before', 'type 2 - Function Level - Before', 'type 3 - Function Level - Before'], inplace=True)
res_pivot.head()

,Model,Repo,type 1 - Function Level - After - H,type 1 - Function Level - After - WH,type 1 - Function Level - Before,type 1 - Repo Level - After - H,type 1 - Repo Level - After - WH,type 1 - Repo Level - Before,type 2 - Function Level - After - H,type 2 - Function Level - After - WH,type 2 - Repo Level - After - H,type 2 - Repo Level - After - WH,type 3 - Function Level - After - H,type 3 - Function Level - After - WH,type 3 - Repo Level - After - H,type 3 - Repo Level - After - WH
3,Artigenz-Coder-DS-6_7B,laconiajs_laconia,0.0,0.0,100.0,74.358974,74.358974,100.000000,0.0,0.0,74.358974,74.358974,0.0,0.0,74.358974,74.358974
2,Artigenz-Coder-DS-6_7B,craftship_codebox-npm,0.0,0.0,100.0,60.073260,28.937729,100.000000,0.0,0.0,91.941392,28.937729,0.0,0.0,93.406593,60.073260
1,Artigenz-Coder-DS-6_7B,StackJanitor,0.0,0.0,100.0,67.567568,67.567568,100.000000,0.0,0.0,67.567568,67.567568,0.0,0.0,67.567568,67.567568
0,Artigenz-Coder-DS-6_7B,JuliaRegistries_Tagbot,0.0,0.0,100.0,0.000000,0.000000,93.333333,0.0,0.0,82.666667,82.666667,NaN,NaN,NaN,NaN
7,CodeQwen1_5-7B-Chat,laconiajs_laconia,0.0,0.0,100.0,74.358974,74.358974,100.000000,0.0,0.0,74.358974,74.358974,0.0,0.0,74.358974,74.358974

In [19]:
res_pivot = res_pivot.rename(columns={
    'type 1 - Repo Level - Before': 'Repo Level - Before',
    'type 1 - Function Level - Before': 'Function Level - Before',
})
final = res_pivot[['Model', 'Repo', 'Repo Level - Before', 'Function Level - Before', 'type 1 - Repo Level - After - WH', 'type 1 - Repo Level - After - H', 'type 1 - Function Level - After - WH', 'type 1 - Function Level - After - H', 'type 2 - Repo Level - After - WH', 'type 2 - Repo Level - After - H', 'type 2 - Function Level - After - WH', 'type 2 - Function Level - After - H', 'type 3 - Repo Level - After - WH', 'type 3 - Repo Level - After - H', 'type 3 - Function Level - After - WH', 'type 3 - Function Level - After - H']]


final = final.reset_index(drop=True)
final = final.round(2)
final.head(20)

,Model,Repo,Repo Level - Before,Function Level - Before,type 1 - Repo Level - After - WH,type 1 - Repo Level - After - H,type 1 - Function Level - After - WH,type 1 - Function Level - After - H,type 2 - Repo Level - After - WH,type 2 - Repo Level - After - H,type 2 - Function Level - After - WH,type 2 - Function Level - After - H,type 3 - Repo Level - After - WH,type 3 - Repo Level - After - H,type 3 - Function Level - After - WH,type 3 - Function Level - After - H
0,Artigenz-Coder-DS-6_7B,laconiajs_laconia,100.00,100.0,74.36,74.36,0.00,0.00,74.36,74.36,0.0,0.00,74.36,74.36,0.00,0.00
1,Artigenz-Coder-DS-6_7B,craftship_codebox-npm,100.00,100.0,28.94,60.07,0.00,0.00,28.94,91.94,0.0,0.00,60.07,93.41,0.00,0.00
2,Artigenz-Coder-DS-6_7B,StackJanitor,100.00,100.0,67.57,67.57,0.00,0.00,67.57,67.57,0.0,0.00,67.57,67.57,0.00,0.00
3,Artigenz-Coder-DS-6_7B,JuliaRegistries_Tagbot,93.33,100.0,0.00,0.00,0.00,0.00,82.67,82.67,0.0,0.00,NaN,NaN,NaN,NaN
4,CodeQwen1_5-7B-Chat,laconiajs_laconia,100.00,100.0,74.36,74.36,0.00,0.00,74.36,74.36,0.0,0.00,74.36,74.36,0.00,0.00
5,CodeQwen1_5-7B-Chat,craftship_codebox-npm,100.00,100.0,28.94,60.07,0.00,0.00,28.94,93.04,0.0,16.67,64.10,95.60,22.22,66.67
6,CodeQwen1_5-7B-Chat,StackJanitor,100.00,100.0,68.47,68.47,11.11,11.11,67.57,70.27,0.0,33.33,67.57,70.27,0.00,33.33
7,CodeQwen1_5-7B-Chat,JuliaRegistries_Tagbot,93.33,100.0,0.00,0.00,0.00,0.00,82.67,86.67,0.0,37.50,NaN,NaN,NaN,NaN
8,DeepSeek-Coder-V2,laconiajs_laconia,100.00,100.0,74.36,74.36,0.00,0.00,74.36,74.36,0.0,0.00,74.36,79.49,0.00,66.67
9,DeepSeek-Coder-V2,craftship_codebox-npm,100.00,100.0,31.87,91.94,0.00,0.00,91.94,94.51,0.0,41.67,94.14,95.60,38.89,66.67
10,DeepSeek-Coder-V2,StackJanitor,100.00,100.0,67.57,81.08,0.00,33.33,67.57,90.09,0.0,62.50,75.68,95.50,0.00,79.17
11,DeepSeek-Coder-V2,JuliaRegistries_Tagbot,93.33,100.0,82.67,86.67,0.00,37.50,82.67,90.67,0.0,50.00,NaN,NaN,NaN,NaN
12,GPT-3_5-Turbo,laconiajs_laconia,100.00,100.0,74.36,74.36,0.00,0.00,74.36,76.92,0.0,33.33,74.36,94.87,0.00,62.50
13,GPT-3_5-Turbo,craftship_codebox-npm,100.00,100.0,60.81,91.94,0.00,0.00,60.81,94.87,0.0,55.56,60.81,95.60,11.11,66.67
14,GPT-3_5-Turbo,StackJanitor,100.00,100.0,67.57,78.38,0.00,0.00,67.57,76.58,0.0,62.50,67.57,76.58,0.00,62.50
15,GPT-3_5-Turbo,JuliaRegistries_Tagbot,93.33,100.0,0.00,84.00,0.00,12.50,82.67,90.67,0.0,50.00,NaN,NaN,NaN,NaN
16,GPT-4,laconiajs_laconia,100.00,100.0,74.36,76.92,0.00,33.33,74.36,100.00,0.0,100.00,74.36,87.18,0.00,20.83
17,GPT-4,craftship_codebox-npm,100.00,100.0,31.87,91.94,0.00,0.00,60.81,62.27,0.0,33.33,93.77,95.60,30.56,66.67
18,GPT-4,StackJanitor,100.00,100.0,67.57,75.68,0.00,0.00,67.57,90.09,0.0,62.50,67.57,86.49,0.00,62.50
19,GPT-4,JuliaRegistries_Tagbot,93.33,100.0,0.00,89.33,0.00,62.50,0.00,90.67,0.0,50.00,NaN,NaN,NaN,NaN

In [20]:
final_df = final.rename(columns={
    'Repo Level - Before': 'Before - Repo Level',
    'Function Level - Before': 'Before - Function Level',
    'type 1 - Repo Level - After - WH': 'After - type 1 - Repo Level - WH',
    'type 1 - Repo Level - After - H': 'After - type 1 - Repo Level - H',
    'type 1 - Function Level - After - WH': 'After - type 1 - Function Level - WH',
    'type 1 - Function Level - After - H': 'After - type 1 - Function Level - H',
    'type 2 - Repo Level - After - WH': 'After - type 2 - Repo Level - WH',
    'type 2 - Repo Level - After - H': 'After - type 2 - Repo Level - H',
    'type 2 - Function Level - After - WH': 'After - type 2 - Function Level - WH',
    'type 2 - Function Level - After - H': 'After - type 2 - Function Level - H',
    'type 3 - Repo Level - After - WH': 'After - type 3 - Repo Level - WH',
    'type 3 - Repo Level - After - H': 'After - type 3 - Repo Level - H',
    'type 3 - Function Level - After - WH': 'After - type 3 - Function Level - WH',
    'type 3 - Function Level - After - H': 'After - type 3 - Function Level - H'
})

final_df.head()

,Model,Repo,Before - Repo Level,Before - Function Level,After - type 1 - Repo Level - WH,After - type 1 - Repo Level - H,After - type 1 - Function Level - WH,After - type 1 - Function Level - H,After - type 2 - Repo Level - WH,After - type 2 - Repo Level - H,After - type 2 - Function Level - WH,After - type 2 - Function Level - H,After - type 3 - Repo Level - WH,After - type 3 - Repo Level - H,After - type 3 - Function Level - WH,After - type 3 - Function Level - H
0,Artigenz-Coder-DS-6_7B,laconiajs_laconia,100.00,100.0,74.36,74.36,0.0,0.0,74.36,74.36,0.0,0.0,74.36,74.36,0.0,0.0
1,Artigenz-Coder-DS-6_7B,craftship_codebox-npm,100.00,100.0,28.94,60.07,0.0,0.0,28.94,91.94,0.0,0.0,60.07,93.41,0.0,0.0
2,Artigenz-Coder-DS-6_7B,StackJanitor,100.00,100.0,67.57,67.57,0.0,0.0,67.57,67.57,0.0,0.0,67.57,67.57,0.0,0.0
3,Artigenz-Coder-DS-6_7B,JuliaRegistries_Tagbot,93.33,100.0,0.00,0.00,0.0,0.0,82.67,82.67,0.0,0.0,NaN,NaN,NaN,NaN
4,CodeQwen1_5-7B-Chat,laconiajs_laconia,100.00,100.0,74.36,74.36,0.0,0.0,74.36,74.36,0.0,0.0,74.36,74.36,0.0,0.0

In [157]:
final_df.to_csv('Processed Test Results.csv', index=False)

---